# Generated by Django 4.0.1 on 2023-07-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_network', '0002_alter_product_created_alter_product_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='release_date',
        ),
    ]
